#############################################################################
# Makefile for building: HRA2017
# Generated by qmake (2.01a) (Qt 4.6.2) on: ne 5 7 19:16:40 2017
# Project:  HRA2017.pro
# Template: app
# Command: /usr/local/bin/qmake -unix -o Makefile HRA2017.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -m64 -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -std=c++11 -m64 -pipe -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/lib64/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)   -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/local/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = 
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mywidget.cpp \
		myview.cpp \
		card.cpp \
		mybutton.cpp \
		objects.cc moc_mywidget.cpp \
		moc_myview.cpp \
		moc_card.cpp \
		moc_mybutton.cpp \
		qrc_res.cpp
OBJECTS       = main.o \
		mywidget.o \
		myview.o \
		card.o \
		mybutton.o \
		objects.o \
		moc_mywidget.o \
		moc_myview.o \
		moc_card.o \
		moc_mybutton.o \
		qrc_res.o
DIST          = /usr/lib64/qt4/mkspecs/common/g++-multilib.conf \
		/usr/lib64/qt4/mkspecs/common/unix.conf \
		/usr/lib64/qt4/mkspecs/common/linux.conf \
		/usr/lib64/qt4/mkspecs/qconfig.pri \
		/usr/lib64/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt4/mkspecs/features/qt_config.prf \
		/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt4/mkspecs/features/default_pre.prf \
		/usr/lib64/qt4/mkspecs/features/release.prf \
		/usr/lib64/qt4/mkspecs/features/default_post.prf \
		/usr/lib64/qt4/mkspecs/features/warn_on.prf \
		/usr/lib64/qt4/mkspecs/features/qt.prf \
		/usr/lib64/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt4/mkspecs/features/moc.prf \
		/usr/lib64/qt4/mkspecs/features/resources.prf \
		/usr/lib64/qt4/mkspecs/features/uic.prf \
		/usr/lib64/qt4/mkspecs/features/yacc.prf \
		/usr/lib64/qt4/mkspecs/features/lex.prf \
		/usr/lib64/qt4/mkspecs/features/include_source_dir.prf \
		HRA2017.pro
QMAKE_TARGET  = HRA2017
DESTDIR       = 
TARGET        = HRA2017

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: HRA2017.pro  /usr/lib64/qt4/mkspecs/linux-g++-64/qmake.conf /usr/lib64/qt4/mkspecs/common/g++-multilib.conf \
		/usr/lib64/qt4/mkspecs/common/unix.conf \
		/usr/lib64/qt4/mkspecs/common/linux.conf \
		/usr/lib64/qt4/mkspecs/qconfig.pri \
		/usr/lib64/qt4/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt4/mkspecs/features/qt_config.prf \
		/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt4/mkspecs/features/default_pre.prf \
		/usr/lib64/qt4/mkspecs/features/release.prf \
		/usr/lib64/qt4/mkspecs/features/default_post.prf \
		/usr/lib64/qt4/mkspecs/features/warn_on.prf \
		/usr/lib64/qt4/mkspecs/features/qt.prf \
		/usr/lib64/qt4/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt4/mkspecs/features/moc.prf \
		/usr/lib64/qt4/mkspecs/features/resources.prf \
		/usr/lib64/qt4/mkspecs/features/uic.prf \
		/usr/lib64/qt4/mkspecs/features/yacc.prf \
		/usr/lib64/qt4/mkspecs/features/lex.prf \
		/usr/lib64/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -unix -o Makefile HRA2017.pro
/usr/lib64/qt4/mkspecs/common/g++-multilib.conf:
/usr/lib64/qt4/mkspecs/common/unix.conf:
/usr/lib64/qt4/mkspecs/common/linux.conf:
/usr/lib64/qt4/mkspecs/qconfig.pri:
/usr/lib64/qt4/mkspecs/features/qt_functions.prf:
/usr/lib64/qt4/mkspecs/features/qt_config.prf:
/usr/lib64/qt4/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt4/mkspecs/features/default_pre.prf:
/usr/lib64/qt4/mkspecs/features/release.prf:
/usr/lib64/qt4/mkspecs/features/default_post.prf:
/usr/lib64/qt4/mkspecs/features/warn_on.prf:
/usr/lib64/qt4/mkspecs/features/qt.prf:
/usr/lib64/qt4/mkspecs/features/unix/thread.prf:
/usr/lib64/qt4/mkspecs/features/moc.prf:
/usr/lib64/qt4/mkspecs/features/resources.prf:
/usr/lib64/qt4/mkspecs/features/uic.prf:
/usr/lib64/qt4/mkspecs/features/yacc.prf:
/usr/lib64/qt4/mkspecs/features/lex.prf:
/usr/lib64/qt4/mkspecs/features/include_source_dir.prf:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile HRA2017.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/HRA20171.0.0 || $(MKDIR) .tmp/HRA20171.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/HRA20171.0.0/ && $(COPY_FILE) --parents mywidget.h myview.h card.h mybutton.h objects.h .tmp/HRA20171.0.0/ && $(COPY_FILE) --parents res.qrc .tmp/HRA20171.0.0/ && $(COPY_FILE) --parents main.cpp mywidget.cpp myview.cpp card.cpp mybutton.cpp objects.cc .tmp/HRA20171.0.0/ && (cd `dirname .tmp/HRA20171.0.0` && $(TAR) HRA20171.0.0.tar HRA20171.0.0 && $(COMPRESS) HRA20171.0.0.tar) && $(MOVE) `dirname .tmp/HRA20171.0.0`/HRA20171.0.0.tar.gz . && $(DEL_FILE) -r .tmp/HRA20171.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mywidget.cpp moc_myview.cpp moc_card.cpp moc_mybutton.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mywidget.cpp moc_myview.cpp moc_card.cpp moc_mybutton.cpp
moc_mywidget.cpp: card.h \
		objects.h \
		myview.h \
		mybutton.h \
		mywidget.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) mywidget.h -o moc_mywidget.cpp

moc_myview.cpp: card.h \
		objects.h \
		myview.h \
		mybutton.h \
		myview.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) myview.h -o moc_myview.cpp

moc_card.cpp: objects.h \
		myview.h \
		card.h \
		mybutton.h \
		card.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) card.h -o moc_card.cpp

moc_mybutton.cpp: mybutton.h
	/usr/lib64/qt4/bin/moc $(DEFINES) $(INCPATH) mybutton.h -o moc_mybutton.cpp

compiler_rcc_make_all: qrc_res.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_res.cpp
qrc_res.cpp: res.qrc \
		Resources/Cover.png \
		Resources/diamonds_9.png \
		Resources/diamonds_10.png \
		Resources/spades_3.png \
		Resources/hearts_4.png \
		Resources/clubs_5.png \
		Resources/hearts_1.png \
		Resources/diamonds_12.png \
		Resources/hearts_6.png \
		Resources/spades_4.png \
		Resources/spades_12.png \
		Resources/hearts_10.png \
		Resources/diamonds_1.png \
		Resources/saveButton.png \
		Resources/undoButton.png \
		Resources/clubs_11.png \
		Resources/spades_6.png \
		Resources/loadButton.png \
		Resources/addGamebutton.png \
		Resources/hearts_9.png \
		Resources/spades_5.png \
		Resources/diamonds_2.png \
		Resources/hearts_2.png \
		Resources/hintButton.png \
		Resources/spades_7.png \
		Resources/clubs_6.png \
		Resources/diamonds_11.png \
		Resources/spades_10.png \
		Resources/diamonds_3.png \
		Resources/hearts_12.png \
		Resources/hearts_5.png \
		Resources/clubs_12.png \
		Resources/diamonds_6.png \
		Resources/diamonds_13.png \
		Resources/spades_8.png \
		Resources/hearts_7.png \
		Resources/clubs_7.png \
		Resources/background.png \
		Resources/spades_13.png \
		Resources/diamonds_4.png \
		Resources/ngButton.png \
		Resources/hearts_11.png \
		Resources/clubs_2.png \
		Resources/placementBorder.png \
		Resources/clubs_1.png \
		Resources/diamonds_7.png \
		Resources/spades_9.png \
		Resources/Joker.png \
		Resources/clubs_8.png \
		Resources/diamonds_5.png \
		Resources/hearts_3.png \
		Resources/clubs_3.png \
		Resources/clubs_10.png \
		Resources/diamonds_8.png \
		Resources/hearts_8.png \
		Resources/spades_2.png \
		Resources/clubs_9.png \
		Resources/rstButton.png \
		Resources/spades_1.png \
		Resources/spades_11.png \
		Resources/hearts_13.png \
		Resources/clubs_4.png \
		Resources/clubs_13.png
	/usr/lib64/qt4/bin/rcc -name res res.qrc -o qrc_res.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

main.o: main.cpp card.h \
		objects.h \
		myview.h \
		mybutton.h \
		mywidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mywidget.o: mywidget.cpp mywidget.h \
		card.h \
		objects.h \
		myview.h \
		mybutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mywidget.o mywidget.cpp

myview.o: myview.cpp myview.h \
		card.h \
		objects.h \
		mybutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o myview.o myview.cpp

card.o: card.cpp card.h \
		objects.h \
		myview.h \
		mybutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o card.o card.cpp

mybutton.o: mybutton.cpp mybutton.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mybutton.o mybutton.cpp

objects.o: objects.cc objects.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o objects.o objects.cc

moc_mywidget.o: moc_mywidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mywidget.o moc_mywidget.cpp

moc_myview.o: moc_myview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_myview.o moc_myview.cpp

moc_card.o: moc_card.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_card.o moc_card.cpp

moc_mybutton.o: moc_mybutton.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mybutton.o moc_mybutton.cpp

qrc_res.o: qrc_res.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_res.o qrc_res.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

